name: camping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^2.31.1
  provider: ^6.1.1
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.2
  dio: ^5.5.0+1
  alica:
    git:
      url: https://github.com/Azamat0411/alice.git
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.19.6
  flutter_advanced_drawer: ^1.3.6

dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Black.ttf
        - asset: assets/font/Montserrat-BlackItalic.ttf
        - asset: assets/font/Montserrat-Bold.ttf
        - asset: assets/font/Montserrat-BoldItalic.ttf
        - asset: assets/font/Montserrat-ExtraBold.ttf
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/font/Montserrat-ExtraLight.ttf
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
        - asset: assets/font/Montserrat-Italic.ttf
        - asset: assets/font/Montserrat-Light.ttf
        - asset: assets/font/Montserrat-LightItalic.ttf
        - asset: assets/font/Montserrat-Medium.ttf
        - asset: assets/font/Montserrat-MediumItalic.ttf
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-SemiBold.ttf
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
        - asset: assets/font/Montserrat-Thin.ttf
        - asset: assets/font/Montserrat-ThinItalic.ttf



